language: bash

sudo: required

services:
  - docker

before_install:
  - docker pull alpinelib/repobuilder:3.2

script:
  - if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then export DEPLOY=true; else export DEPLOY=false;fi
  - docker run --rm -e ABUILD_SSHKEY="$SSHABUILDKEY" -e DEPLOY=$DEPLOY builder build main
