language: bash

sudo: required

services:
  - docker

before_install:
  - docker pull alpinelib/repobuilder:3.2
  - docker pull alpinelib/repobuilder:edge
  - docker run alpinelib/repobuilder:3.2 build 3.2
  - docker run alpinelib/repobuilder:edge build edge

script:
    - docker ps -a
